### ISSUE TITLE
Its a scam!

### ISSUE THREAD

**Issue by ghost** [eiffelhax/enet-proxy-edited-version-for-growtopia-v.-3.51#1]
Do not download this shit! It doesnt have the  IPV6 version for enet.. See the server ip and port, they are not real ip and port of the server. This dud trys to scam us lol! Use WinMerge to check difference between original proxy and this shit. You will understand!

**Comment by eiffelhax** [comment]
Bro I don’t understand how can I scam u lol btw I download this from ama6nen and I just edited old gt version to current version lol

**Comment by fxip** [comment]
> Do not download this shit! It doesnt have the IPV6 version for enet.. See the server ip and port, they are not real ip and port of the server. This dud trys to scam us lol! Use WinMerge to check difference between original proxy and this shit. You will understand!

Bro I don’t understand how can I scam u lol btw I download this from ama6nen and I just edited old gt version to current version lol

**Comment by ghost** [comment]
Well simply, you are just a lier. Can you explain us why you did changed the ip and port of the server? And the extra is its not about fkking version dud. Ubisoft just changed the enet they were using. Its supports IPV6 now. And all of your enet files are same with original proxy files. I can bet about the new port and ip just connects proxy to your fake server.

**Comment by ghost** [comment]
And you are didnt changed just the version. There is few changes in your code. Its simply to find with WinMerge as I said.

**Comment by fxip** [comment]
> Well simply, you are just a lier. Can you explain us why you did changed the ip and port of the server? And the extra is its not about fkking version dud. Ubisoft just changed the enet they were using. Its supports IPV6 now. And all of your enet files are same with original proxy files. I can bet about the new port and ip just connects proxy to your fake server.

I still don’t understand what are you trying to say cuz my English is not good but you say I scam how I can scam? Like hack your pc or steal your account? Lol and what you mean connect proxy to my fake server I don’t understand that also lol

**Comment by ghost** [comment]
Dont play idiot or just use translate. Your project doesnt uses real port and ip of the server. It just connects somewhere else. So when people gonna use this proxy they will be just sending you the login packet. And guess what? Login packet includes growId and growPass. You are just and scammer dud...

**Comment by fxip** [comment]
> Dont play idiot or just use translate. Your project doesnt uses real port and ip of the server. It just connects somewhere else. So when people gonna use this proxy they will be just sending you the login packet. And guess what? Login packet includes growId and growPass. You are just and scammer dud...

I’m not lol if you check my code you can see that everything is same as ama6nen original but I changed name and version lol

**Comment by ghost** [comment]
https://github.com/eiffelhax/enet-proxy-edited-version-for-growtopia-v.-3.51/blob/191c79de2f6a65abb15d9ae145d9386223cddb87/proxy/server.h#L22
and
https://github.com/eiffelhax/enet-proxy-edited-version-for-growtopia-v.-3.51/blob/191c79de2f6a65abb15d9ae145d9386223cddb87/proxy/server.h#L23

Explain now idiot. I wont let you scam anyone.

**Comment by fxip** [comment]
> https://github.com/eiffelhax/enet-proxy-edited-version-for-growtopia-v.-3.51/blob/191c79de2f6a65abb15d9ae145d9386223cddb87/proxy/server.h#L22
> 
> 
> and
> https://github.com/eiffelhax/enet-proxy-edited-version-for-growtopia-v.-3.51/blob/191c79de2f6a65abb15d9ae145d9386223cddb87/proxy/server.h#L23

well I didn’t code that try to check with the original from ama6nen is it same?

**Comment by ghost** [comment]
https://github.com/ama6nen/enetproxy/blob/7cf8630b88f6976eda0c5ff7ec398529607c8982/proxy/server.h#L22
and
https://github.com/ama6nen/enetproxy/blob/7cf8630b88f6976eda0c5ff7ec398529607c8982/proxy/server.h#L23
Guess what? Its not fkking same lmao!

**Comment by fxip** [comment]
Well the files that I upload is from ama6nen old version with old ip and old port but I changed the name and gt version

**Comment by ghost** [comment]
Change the port and ip to real one if it was a mistake. And this proxy wont work dude. You need to update enet to new enet that supports IPV6.

**Comment by fxip** [comment]
> Change the port and ip to real one if it was a mistake. And this proxy wont work dude. You need to update enet to new enet that supports IPV6.

Ok bro I will fix it ty bro

**Comment by ghost** [comment]
Np

**Comment by fxip** [comment]
> Np

hello bro I fixed it if there is anything I need to fix you can tell me

**Comment by fxip** [comment]
> Np

if you check and everything are fine I want you to close thread ty

**Comment by ghost** [comment]
Its fine about port and ip. But no one can use this proxy because you need to update enet to IPV6 supported enet. Anyways good luck!
